openapi: 3.0.1
info:
  title: Delilah Restó
  description: Esta API REST le permitirá interactuar con nuestro restaurante Delilah Restó.
    podrás registrarte, ver el listado de nuestros productos y realizar tu pedido.
    nuestros administradores podrán recibir y actualizar el estado de los pedidos.
    (CRUD)
  contact:
    email: valentinavilladarendon@gmail.com
  version: 1.0.0
  license:
    name: MIT
    url: https://github.com/Valentina-vr/Delilah_rest-/blob/main/LICENSE
servers:
- url: http://localhost:3000/
tags:
- name: Create User
  description: Creacion y registro de usuarios
- name: Login User
  description: Ingreso de usuarios registrados
- name: Create Requests
  description: Creacion de nuevos pedidos
- name: Update Requests
  description: Actualizacion del estado de los pedidos
- name: List Products
  description: Obtener lista de productos
- name: Create Product
  description: Creacion de un nuevo producto
- name: Update Products
  description: Actualizacion de productos existentes
- name: List Orders
  description: Obtener listado de ordenes que se han realizado
- name: Delete Products
  description: Eliminacion de productos
- name: Delete Order
  description: Eliminacion de ordenes
paths:
  /users/create:
    post:
      tags:
      - Create User
      summary: Crear nuevo usuario en la base de datos
      description: Petición de creación de usuario en la base de datos
      operationId: addUser
      requestBody:
        description: Datos del usuario a registrar
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateUsers'
        required: true
      responses:
        200:
          description: Successfully registered user
          content: {}
        400:
          description: This email is already registered, try another
          content: {}
        406:
          description: Please, fill in all the fields
          content: {}
        500:
          description: Oh oh, we have server problems, please try again later
          content: {}
      x-codegen-request-body-name: body
  /users/login:
    post:
      tags:
      - Login User
      summary: Ingreso de usuarios registrados
      description: Ingreso de usuarios registrados en la base de datos
      operationId: loginUser
      requestBody:
        description: Email y password del usuario registrado
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/login'
        required: true
      responses:
        200:
          description: Successful Entry
          content:
            application/json:
                schema:
                  example: 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NywibmFtZSI6IkNsYXVkaWEgUmVuZG9uIiwiZW1haWwiOiJjbGF1ZGlhcmVuZG9uQGdtYWlsLmNvbSIsInBhc3N3b3JkIjoiMTIzNDU2Nzg5IiwidGVsZXBob25lIjoiOTg3NDU2MzIxIiwiYWRkcmVzcyI6IkNMIDUzIE4xMjM0IiwiaXNBZG1pbiI6dHJ1ZSwiaWF0IjoxNjA0MTY1OTQ4fQ.R12Qmp8awpamijBB0wyVvmh0ufnlvuMU6kGzOW2_Enk'
        401:
          description: Invalid username or password
          content: {}
        406:
          description: Please, fill in all the fields
          content: {}
      security:
      - bearerAuth: []
      x-codegen-request-body-name: body
  /request/create:
    post:
      tags:
      - Create Requests
      summary: Crear un nuevo pedido
      description: Creacion de pedidos, debe estar autenticado para realizar esta
        operación
      operationId: addRequest
      requestBody:
        description: Pedido
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/createRequests'
        required: true
      responses:
        200:
          description: Successfully registered order
          content: {}
        400:
          description: User could not be verified
          content: {}
        401:
          description: You must enter with your username and password to use this service.
          content: {}
        406:
          description: Invalid fields
          content: {}
        500:
          description: Oh oh, we have server problems, please try again later
          content: {}
      security:
      - bearerAuth: []
      x-codegen-request-body-name: body
  /request/update/{requestId}:
    patch:
      tags:
      - Update Requests
      summary: Actualizar pedidos
      description: Actualizar pedidos por Id
      operationId: updateRequest
      parameters:
      - name: requestId
        in: path
        description: Id del pedido a actualizar
        required: true
        schema:
          type: integer
      requestBody:
        description: Actualizar estado del pedido
        content:
          application/json:
            schema:
              type: object
              properties:
                status:
                  type: "string"
      responses:
        401:
          description: You must enter with your username and password to use this service.
          content: {}
        403:
          description: insufficient permissions
          content: {}
        404:
          description: Data not found, your order could not be updated.
          content: {}
        406:
          description: Invalid fields
          content: {}
        500:
          description: Oh oh, we have server problems, please try again later
          content: {}
      security:
      - bearerAuth: []
  /product/getall:
    get:
      tags:
      - List Products
      summary: Obtener lista de todos los productos disponibles
      description: Obtiene la lsita de productos disponibles para los usuarios registrados
      operationId: getProductList
      responses:
        200:
          description: Successful consultation
          content:
            application/json:
              schema:
                type: object
        401:
          description: You must enter with your username and password to use this service.
          content: {}
        500:
          description: Oh oh, we have server problems, please try again later
          content: {}
      security:
        - bearerAuth: []
  /product/create:
    post:
      tags:
      - Create Product
      summary: Crear un nuevo producto
      description: Creacion de productos
      operationId: createProduct
      requestBody:
        description: Producto
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/createProducts'
        required: true
      responses:
        200:
          description: Product added successfully
          content: {}
        401:
          description: You must enter with your username and password to use this service.
          content: {}
        403:
          description: insufficient permissions
          content: {}
        406:
          description: Please fill all fields
          content: {}
        500:
          description: Oh oh, we have server problems, please try again later
          content: {}
      x-codegen-request-body-name: body
  /product/update/{productId}:
    patch:
      tags:
      - Update Products
      summary: Actualizar productos
      description: Actualizar productos por Id
      operationId: updateProduct
      parameters:
      - name: productId
        in: path
        description: Id del producto a actualizar
        required: true
        schema:
          type: integer
      requestBody:
        description: Actualizar caracteristicas del producto
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/createProducts"
              
      responses:
        401:
          description: Debes ingresar con tu usuario y contraseña para utilizar este
            servicio
          content: {}
        403:
          description: insufficient permissions
          content: {}
        404:
          description: Data not found, could not update the product.
          content: {}
        500:
          description: Oh oh, we have server problems, please try again later
          content: {}
      security:
        - bearerAuth: []
  /request/orders:
    get:
      tags:
      - List Orders
      summary: Obtener lista de todos las ordenes
      description: Obtiene la lista de todas las ordenes con el producto y la cantidad
      operationId: getOrders
      responses:
        200:
          description: Successful consultation
          content:
            application/json:
              schema:
                type: object
        500:
          description: Oh oh, we have server problems, please try again later
          content: {}      
      security:
        - bearerAuth: []
  /requests/delete/{requestId}:
    delete:
      tags:
        - Delete Order
      summary: Eliminar pedido por ID
      description: Eliminar pedido por ID
      operationId: deleteRequest
      parameters:
        - name: requestId
          in: path
          description: Id del pedido a eliminar
          required: true
          schema:
            type: integer
      responses:
        200:
          description: Order removed successfully
        400:
          description: Please submit the order ID.
        401:
          description: You must enter with your username and password to use this service.
        403:
          description: You must have administrator permissions to make this request.
        404:
          description: Order not found, please verify
        500:
          description: Oh oh, we have problems, please try again later.
      security:
        - bearerAuth: []
  /product/delete/{productId}:
    delete:
      tags:
      - Delete Products
      summary: Eliminar producto
      description: Eliminar producto por ID
      operationId: deleteProduct
      parameters:
      - name: productId
        in: path
        description: Id del producto a eliminar
        required: true
        schema:
          type: integer
      responses:
        200:
          description: Producto eliminado satisfactoriamente
          content: {}
        401:
          description: You must enter with your username and password to use this service.
          content: {}
        403:
          description: Debes tener permisos de administrador para realizar esta petición
          content: {}
        404:
          description: Product not found, please check the fields
          content: {}
        500:
          description: Oh oh, we have server problems, please try again later
          content: {}
components:
  schemas:
    CreateUsers:
      type: object
      properties:
        name:
          type: string
        email:
          type: string
        password:
          type: string
        telephone:
          type: string
        address:
          type: string
        isAdmin:
          type: boolean
    login:
      type: object
      properties:
        email:
          type: string
        password:
          type: string
    createRequests:
      type: object
      properties:
        pay_method:
          type: string
        userId:
          type: integer
        products:
          type: array
          items:
            type: object
            properties:
              productId:
                type: integer
              quantity:
                type: integer
    createProducts:
      type: object
      properties:
        name:
          type: string
        description:
          type: string
        type:
          type: string
        price:
          type: string
        imagen:
          type: string
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT